name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload all files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
